blank_issues_enabled: true
contact_links:
  - name: Telegram Desktop issue
    url: https://github.com/telegramdesktop/tdesktop/issues/new/choose
    about: Issues of original Telegram Desktop app.
  - name: Official app issue
    url: https://bugs.telegram.org
    about: Any bug report or feature request not about Telegram Desktop.
  - name: Question
    url: https://t.me/kotatochat
    about: Ask a question.
